### PR TITLE
The Poker Probability Add files via upload

### PR DESCRIPTION
**Pull request by tcorea**
This is the probability algorithm class using the Cards, Rank and Suit classes

### CODE REVIEW

**Review by vlyandra — CHANGES_REQUESTED** [review]
Please put classes in a package.

**Comment by tcorea** [comment]
> Please put classes in a package.

I added the calculator package. if thats incorrect then im lost sorry. 





[probabilityAlgorithm.zip](https://github.com/vlyandra/PokerProjectCapstone/files/3100464/probabilityAlgorithm.zip)

**Comment by vlyandra** [comment]
You need to commit your changes and push your branch with the new code so I can see it.

**Comment by tcorea** [comment]
> You need to commit your changes and push your branch with the new code so I can see it.

so just change/edit the code and then do another pull request ?

**Review by vlyandra — APPROVED** [review]
LGTM

**Pull request merged**
