### PR TITLE
Cleanup calculator panel

### PR DESCRIPTION
**Pull request by vlyandra**
New and improved calculator panel!
- Add/remove community cards
- Probability calculation hooked up
- You can only save when all community cards have been selected, for reporting purposes

### CODE REVIEW

**Comment by Poockins** [comment]
Pulled and it looks good on my end. I think we might just need to tweak the odds calculation as I am getting numbers that are not percentages but it is also getting very late in the day for possibly a difficult change. Just figure I would add it incase it was just a missing *100 or something

**Comment by vlyandra** [comment]
The probability calculation is really off but at this point that's on me for not sanity checking when it was in development. If you change the cards around you can see that it is actually a percentage, just a very confusing one.

**Comment by vlyandra** [comment]
Also, can I get a review approval if we're good to go?

**Comment by Poockins** [comment]
Excellent, good to go

**Comment by Poockins** [comment]
Is it the button with the clipboard and <- on it?

**Comment by vlyandra** [comment]
Admin merging.

**Pull request merged**
